<a href="https://colab.research.google.com/github/Gkcoli/MLThings/blob/main/ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY


In [66]:
!pip install numpy

In [67]:
import numpy as np

In [68]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [69]:
arr [1]

2

In [70]:
arr = np.array([[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
arr.shape

(3, 2)

In [72]:
arr = np.array(([1,2], [3,4], [5,6]), dtype=np.float64)
arr.dtype

dtype('float64')

#String Functions

In [73]:
arr1 = np.array(["Hello ", "Hi "])
arr2 = np.array (["Medtech ", "Please "])

In [74]:
arrstring = np.char.add(arr1, arr2)
arrstring

array(['Hello Medtech ', 'Hi Please '], dtype='<U14')

In [75]:
arr1 = np.array(["Hello"])
arr2 = np.array([3])

In [76]:
arrstring = np.char.multiply(arr1, 3)
arrstring

array(['HelloHelloHello'], dtype='<U15')

In [77]:
namearray = np.array(["Gian Colinares"])

In [78]:
arr = np.char.split(namearray)
arr

array([list(['Gian', 'Colinares'])], dtype=object)

#Array Manipulation


In [79]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
arr5 = np.arange(20)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [81]:
arr5 = arr5.reshape(4,5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [82]:
arr = np.arange(8)
arr2 = arr.reshape(2,2,2)
print(arr2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [83]:
arr2[0][0][0]

0

#ARITHMETIC OPERATIONS

In [86]:
a = np.arange(9).reshape (3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
b = np.multiply(a, 3)
b

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [89]:
c = np.subtract(a, b)
c

array([[  0,  -2,  -4],
       [ -6,  -8, -10],
       [-12, -14, -16]])

In [90]:
d = np.add(a,b)
d

array([[ 0,  4,  8],
       [12, 16, 20],
       [24, 28, 32]])

#OTHER FUNCTIONS


In [91]:
a = np.linspace(1,3,10)
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [96]:
a = np.array([(1,2,3),(3,4,5)])
print(a.sum(axis=1))

[ 6 12]


In [97]:
a = np.array([(1,2,3),(3,4,5)])
print(a.sum(axis=0))

[4 6 8]


In [93]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


In [94]:
print(np.std(a))

1.2909944487358056
